<a href="https://colab.research.google.com/github/vinoothna005/Internship/blob/main/House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data = pd.read_csv('/content/House.csv', encoding='latin-1')

data

,Unnamed: 0,Bedroom,Bathroom,Location,Size,status,Facing,Type,Price
0,0,3,3,Poranki,1587,Ready to move,West,Apartment,55.50
1,1,2,2,Poranki,1450,Ready to move,0,Apartment,48.00
2,2,2,2,Kankipadu,1290,Under Construction,NorthEast,Independent House,50.00
3,3,2,4,PNT Colony,1400,Ready to move,0,Independent House,72.00
4,4,2,2,Labbipet,950,Ready to move,East,Apartment,60.00
...,...,...,...,...,...,...,...,...,...
1111,1111,3,3,Vidhyadharpuram,1600,Under Construction,West,Residential Plot,95.00
1112,1112,6,7,Penamaluru,3700,Ready to move,0,Apartment,110.00
1113,1113,0,0,Kankipadu,1782,Resale,0,Apartment,16.83
1114,1114,0,0,Poranki,1800,Resale,West,Independent House,33.00
1115,1115,0,0,Kankipadu,1500,Resale,0,Apartment,20.00

In [ ]:
data.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bedroom   1116 non-null   int64
 1   Bathroom  1116 non-null   int64
 2   Location  1116 non-null   object
 3   Size      1116 non-null   int64
 4   status    1116 non-null   object
 5   Facing    1116 non-null   object
 6   Type      1116 non-null   object
 7   Price     1116 non-null   float64
dtypes: float64(1), int64(3), object(4)
memory usage: 69.9+ KB

In [ ]:
data['Location'].unique()

array(['Poranki', 'Kankipadu', 'PNT Colony', 'Labbipet', 'Gannavaram',
       'Gunadala', 'Gollapudi', 'Enikepadu', 'Benz Circle',
       'Vidhyadharpuram', 'Penamaluru', 'Payakapuram'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()

In [ ]:
#data['Location'] = encoder.fit_transform(data['Location'])

In [ ]:
data.columns

Index(['Bedroom', 'Bathroom', 'Location', 'Size', 'status', 'Facing', 'Type',
       'Price'],
      dtype='object')

In [ ]:
from pandas.core.interchange.dataframe_protocol import Column
for col in data.columns:
  if data[col].dtype == 'object':
    # data[col] = encoder.fit_transform(data[col])
    encoder=LabelEncoder()
    encoder.fit(data[col])
    print('Column:',col)
    print('Original categories:', encoder.classes_)
    print('Encoded values:', encoder.transform(encoder.classes_))
    print('\n')
    data[col]=encoder.fit_transform(data[col])

Column: Location
Original categories: ['Benz Circle' 'Enikepadu' 'Gannavaram' 'Gollapudi' 'Gunadala' 'Kankipadu'
 'Labbipet' 'PNT Colony' 'Payakapuram' 'Penamaluru' 'Poranki'
 'Vidhyadharpuram']
Encoded values: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Column: status
Original categories: ['Ready to move' 'Resale' 'Under Construction']
Encoded values: [0 1 2]


Column: Facing
Original categories: ['0' 'East' 'NorthEast' 'West']
Encoded values: [0 1 2 3]


Column: Type
Original categories: ['Apartment' 'Independent House' 'Residential Plot']
Encoded values: [0 1 2]

In [ ]:
data

      Bedroom  Bathroom  Location  Size  status  Facing  Type   Price
0           3         3        10  1587       0       3     0   55.50
1           2         2        10  1450       0       0     0   48.00
2           2         2         5  1290       2       2     1   50.00
3           2         4         7  1400       0       0     1   72.00
4           2         2         6   950       0       1     0   60.00
...       ...       ...       ...   ...     ...     ...   ...     ...
1111        3         3        11  1600       2       3     2   95.00
1112        6         7         9  3700       0       0     0  110.00
1113        0         0         5  1782       1       0     0   16.83
1114        0         0        10  1800       1       3     1   33.00
1115        0         0         5  1500       1       0     0   20.00

[1116 rows x 8 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bedroom   1116 non-null   int64
 1   Bathroom  1116 non-null   int64
 2   Location  1116 non-null   int64
 3   Size      1116 non-null   int64
 4   status    1116 non-null   int64
 5   Facing    1116 non-null   int64
 6   Type      1116 non-null   int64
 7   Price     1116 non-null   float64
dtypes: float64(1), int64(7)
memory usage: 69.9 KB

In [ ]:
x = data.drop('Price', axis=1)
#x = data[['Bedroom', 'Bathroom', .....]]
y = data['Price']

In [ ]:
x

      Bedroom  Bathroom  Location  Size  status  Facing  Type
0           3         3        10  1587       0       3     0
1           2         2        10  1450       0       0     0
2           2         2         5  1290       2       2     1
3           2         4         7  1400       0       0     1
4           2         2         6   950       0       1     0
...       ...       ...       ...   ...     ...     ...   ...
1111        3         3        11  1600       2       3     2
1112        6         7         9  3700       0       0     0
1113        0         0         5  1782       1       0     0
1114        0         0        10  1800       1       3     1
1115        0         0         5  1500       1       0     0

[1116 rows x 7 columns]

In [ ]:
y

0        55.50
1        48.00
2        50.00
3        72.00
4        60.00
         ...
1111     95.00
1112    110.00
1113     16.83
1114     33.00
1115     20.00
Name: Price, Length: 1116, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.3,
                                                    random_state=123)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
model.score(x_train, y_train)

0.7565568190138833

In [ ]:
model.score(x_test, y_test)

0.7667082828510934

In [ ]:
y_pred= model.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.7667082828510934

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bedroom   1116 non-null   int64
 1   Bathroom  1116 non-null   int64
 2   Location  1116 non-null   int64
 3   Size      1116 non-null   int64
 4   status    1116 non-null   int64
 5   Facing    1116 non-null   int64
 6   Type      1116 non-null   int64
 7   Price     1116 non-null   float64
dtypes: float64(1), int64(7)
memory usage: 69.9 KB

In [ ]:
bed = int(input('Enter No of Bedrooms : '))
bath = int(input('Enter No of Bathrooms : '))
loc = int(input('Enter Location : '))
size = int(input('Enter Size in sq feet : '))
status = int(input('Enter Status : '))
face = int(input('Enter Facing : '))
Type = int(input('Enter Property Type : '))

Enter No of Bedrooms : 4
Enter No of Bathrooms : 4
Enter Location : 75
Enter Size in sq feet : 1600
Enter Status : 0
Enter Facing : 1
Enter Property Type : 1

In [ ]:
import numpy as np

input_data = np.array([[bed, bath, loc, size, status, face, Type]])

In [ ]:
prediction = model.predict(input_data)[0]

print('Predicted Price : ₹', abs(prediction), 'Lakhs')

Predicted Price : ₹ 113.98149678090013 Lakhs